### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by 1371030** [lengain/ExampleForLightNetwork#1]
以下代码报错
let code : Int = (jsonData as! [String : Any])["code"] as! Int
                if code == 200 {
                    success?(self, jsonData)
                }else {
                    failure?(self, ExampleServerError.invalidParameter)
                }
                
                
Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by lengain** [comment]
这个是取值强制解包的时候出的错，改成？或者看看数据提供的是否正确

**Comment by lengain** [comment]
这个是取值强制解包的时候出的错，改成？或者看看数据提供的是否正确
